### ISSUE TITLE
How do I use this to log an error that I have already caught?

### ISSUE THREAD

**Issue by papb** [ehmicky/log-process-errors#36]
I have an `error` variable that I caught from somewhere else. I would like to log it cleanly to console just like this library does. However, from the readme, it looks like this library only acts on uncaught errors. Does this library also provide a way to do this?

**Comment by ehmicky** [comment]
Hi @papb :wave: 

At the moment, the logic related to error formatting is not decoupled from the logic related to error handling, so you would need to handle the errors using `log-process-errors` to benefit from the error formatting.

One thing to keep in mind is that the error formatting needs not only the error instance, but any properties passed to the `process` event. For example, in `process.on('unhandledPromise', (error, promise) => {...}`, both `error` and `promise` are printed by the error formatter (since they are both interesting). So if we were to decouple error formatting, users would need to pass those arguments along as well. That's not a huge concern, I am just pointing it out.

Decoupling the formatting logic is not completely straightforward though, so I'd like to ask you: would the [`log` option](https://github.com/ehmicky/log-process-errors/blob/master/docs/API.md#log) be a solution for you? This would require you to catch the error using `log-process-errors`, but you would still be able to run your custom logic.

**Comment by papb** [comment]
Hello, thank you for the fast reply. No, the log option wouldn't work for me; I have already caught the error within a `try-catch` block.

However, I decided I don't really need this for now, so don't worry about it :)
