### ISSUE TITLE
Casing change in 10.0.0 release notes

### ISSUE THREAD

**Issue by papb** [ehmicky/log-process-errors#41]
Hello, I was reading the [10.0.0 release notes](https://github.com/ehmicky/log-process-errors/releases/tag/10.0.0) and noticed that the "before" code uses `"UncaughtException"` while the "after" code uses `"uncaughtException"` instead (changed from PascalCase to camelCase). Why? I think it would be good to have that better described in the release notes. Or is it a typo? Thanks!

**Comment by ehmicky** [comment]
Hi @papb,

The case of the event did change as you described. The reason is: it now matches the case used by Node.js `process.on()` event. Before it was capitalized because it was set as the `error.name`. Now, the `event` name is passed as a second argument to `options.onError()` and `error.name` is left unchanged.

I have updated the release notes to make it clearer.

If there is anything that is not clear, please let me know. Thanks for creating this issue!
